### ISSUE TITLE
Safari/OS X Monterei: Problems opening popups (modals)

### ISSUE THREAD

**Issue by ut** [a-thousand-channels/a1000c-map-client#45]
Clicking on a place on the map does not open the popup!

**Comment by Jarami110d** [comment]
[Log] Mounted**** (62fddec.js, line 1)
[Log] jumpToMap  (62fddec.js, line 1)
[Log] onMapReady: NO fitBounds w/0 (62fddec.js, line 1)
[Log] e {, …} (62fddec.js, line 1)
[Log] fetch... (62fddec.js, line 1)
[Log] {__ob__: Nt} (62fddec.js, line 1)
[Log] data already fetched (62fddec.js, line 1)
[Log]  (62fddec.js, line 1)
[Log] scrollBehavior (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main/", hash: "", query: {}, …} (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main", hash: "#map", query: {}, …} (03e3889.js, line 2)
[Log] Section: #map (03e3889.js, line 2)
[Log] Scroll non smooth to 0/1669 (03e3889.js, line 2)
[Log] Place: #undefined (03e3889.js, line 2)
[Log] fetch... success (62fddec.js, line 1)
[Log] Data for a single layer (62fddec.js, line 1)
[Error] TypeError: undefined is not an object (evaluating 'this.data.layer') — 62fddec.js:1:53517
	re (6b2642c.js:2:11904)
	ne (6b2642c.js:2:11815)
	te (6b2642c.js:2:11465)
	(anonymous function) (6b2642c.js:2:36129)
	r (6b2642c.js:2:65852)
	(anonymous function) (6b2642c.js:2:27392)
	(anonymous function) (6b2642c.js:2:28275)
	An (6b2642c.js:2:26374)
	(anonymous function) (6b2642c.js:2:12574)
	ue (6b2642c.js:2:12014)
	promiseReactionJob
[Error] TypeError: undefined is not an object (evaluating 'this.data.layer') — 62fddec.js:1:53517
	re (6b2642c.js:2:11904)
	ne (6b2642c.js:2:11815)
	te (6b2642c.js:2:11465)
	(anonymous function) (6b2642c.js:2:36129)
	r (6b2642c.js:2:65852)
	(anonymous function) (6b2642c.js:2:27392)
	(anonymous function) (6b2642c.js:2:28275)
	An (6b2642c.js:2:26374)
	(anonymous function) (6b2642c.js:2:12574)
	ue (6b2642c.js:2:12014)
	promiseReactionJob
[Warning] The resource https://a-thousand-channels.github.io/fgtq-client/_nuxt/static/1639918995/main/payload.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource https://a-thousand-channels.github.io/fgtq-client/_nuxt/static/1639918995/manifest.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Log] <-- top #map (62fddec.js, line 1)
[Log] scrollBehavior (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main", hash: "#map", query: {}, …} (03e3889.js, line 2)
[Log] {name: "index", meta: {}, path: "/", hash: "", query: {}, …} (03e3889.js, line 2)
[Log] undefined (b63bf4c.js, line 1)
[Log] {} (b63bf4c.js, line 1)
[Log] https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json (b63bf4c.js, line 1)
[Log] scrollBehavior (03e3889.js, line 2)
[Log] {name: "index", meta: {}, path: "/", hash: "", query: {}, …} (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main", hash: "#map", query: {layer: "https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json"}, …} (03e3889.js, line 2)
[Log] Section: #map (03e3889.js, line 2)
[Log] Mounted**** (62fddec.js, line 1)
[Log] {layer: "https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json"} (62fddec.js, line 1)
[Log] https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json (62fddec.js, line 1)
[Log] jumpToMap #map (62fddec.js, line 1)
[Log] onMapReady: NO fitBounds w/0 (62fddec.js, line 1)
[Log] e {, …} (62fddec.js, line 1)
[Log] fetch... (62fddec.js, line 1)
[Log] {__ob__: Nt} (62fddec.js, line 1)
[Log] data already fetched (62fddec.js, line 1)
[Log] https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json (62fddec.js, line 1)
[Log] scrollBehavior (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main", hash: "#map", query: {layer: "https://orte.link/public/maps/from-gay-to-queer/layers/tunte-terror-tour-93.json"}, …} (03e3889.js, line 2)
[Log] {name: "main", meta: {}, path: "/main", hash: "#map", query: {}, …} (03e3889.js, line 2)
[Log] Section: #map (03e3889.js, line 2)
[Log] Scroll non smooth to 0/1792 (03e3889.js, line 2)
[Log] Place: #undefined (03e3889.js, line 2)
[Log] Scroll non smooth to 0/1792 (03e3889.js, line 2)
[Log] Place: #undefined (03e3889.js, line 2)
[Log] fetch... success (62fddec.js, line 1)
[Log] Data for a single layer (62fddec.js, line 1)
[Log] Data for a map with 1 accessible layer (62fddec.js, line 1)
[Log] Layer Map with 5 places and 4 Relations (62fddec.js, line 1)
[Log] Check for data.layer w/1 layer(s) (62fddec.js, line 1)
[Log] places_with_relations: 1 (62fddec.js, line 1)
[Log] Relation_from ID:  729 (62fddec.js, line 1)
[Log] places_with_relations: 1 (62fddec.js, line 1)
[Log] Relation_from ID:  731 (62fddec.js, line 1)
[Log] places_with_relations: 1 (62fddec.js, line 1)
[Log] Relation_from ID:  732 (62fddec.js, line 1)
[Log] places_with_relations: 1 (62fddec.js, line 1)
[Log] Relation_from ID:  733 (62fddec.js, line 1)
[Log] onLayerVisible (62fddec.js, line 1)
[Log] 63 (62fddec.js, line 1)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1365.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1364.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1366.png, line 0)
[Log] onclick (62fddec.js, line 1)
[Log] 729 (62fddec.js, line 1)
[Log] marker-729 (62fddec.js, line 1)
[Log] {, …} (62fddec.js, line 1)
[Log] Clicked place: 1. Stopp: Homolandwoche 1993 (62fddec.js, line 1)
[Log] Clicked place ID: 729 (62fddec.js, line 1)
[Log] Clicked place index: 0 (62fddec.js, line 1)
[Log] Clicked layer title: Tunten-Terror-Tour '93 (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] this.data.state: true (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] onclick (62fddec.js, line 1)
[Log] 729 (62fddec.js, line 1)
[Log] marker-729 (62fddec.js, line 1)
[Log] {, …} (62fddec.js, line 1)
[Log] Clicked place: 1. Stopp: Homolandwoche 1993 (62fddec.js, line 1)
[Log] Clicked place ID: 729 (62fddec.js, line 1)
[Log] Clicked place index: 0 (62fddec.js, line 1)
[Log] Clicked layer title: Tunten-Terror-Tour '93 (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] this.data.state: false (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] onclick (62fddec.js, line 1)
[Log] 730 (62fddec.js, line 1)
[Log] marker-730 (62fddec.js, line 1)
[Log] {, …} (62fddec.js, line 1)
[Log] Clicked place: 5. Stopp: KZ-Gedenkstätte Neuengamme (62fddec.js, line 1)
[Log] Clicked place ID: 730 (62fddec.js, line 1)
[Log] Clicked place index: 1 (62fddec.js, line 1)
[Log] Clicked layer title: Tunten-Terror-Tour '93 (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] this.data.state: true (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] onclick (62fddec.js, line 1)
[Log] 730 (62fddec.js, line 1)
[Log] marker-730 (62fddec.js, line 1)
[Log] {, …} (62fddec.js, line 1)
[Log] Clicked place: 5. Stopp: KZ-Gedenkstätte Neuengamme (62fddec.js, line 1)
[Log] Clicked place ID: 730 (62fddec.js, line 1)
[Log] Clicked place index: 1 (62fddec.js, line 1)
[Log] Clicked layer title: Tunten-Terror-Tour '93 (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)
[Log] this.data.state: false (62fddec.js, line 1)
[Log] Clicked layer index: 0 (62fddec.js, line 1)

**Comment by Jarami110d** [comment]
Exemple or error in Safari loading content- Pop-up infos on Map. example from Tunten Terror Tour-93
https://a-thousand-channels.github.io/fgtq-client/main#map

**Comment by ut** [comment]
Thanks, @Jarami110d !

I think I found the problem.... Every time a marker (one of the circles on the map) is clicked the display value for the modals (popups) and for the container containing all popups, set. If the modal is visible is stored in a value called "state"

Normal behaviour is

state: false 
-- click event --
state: true

This works correctly on FF and Chrome and older safarifs

But on newest Mac OS + Safari, it returns 

state: true
-- click event --
state: false

(Sidenote: generic "state" should be renamed to "visible")

**Comment by ut** [comment]
I'm gonna do some research and do a fix

**Comment by ut** [comment]
This is fixed now! 

Technical infos: Around all modals is a div-wrapper, the display value (true/false) was not set (could not be set dynamic, since "Vue does not allow dynamically adding new root-level reactive properties to an already created instance.") and safari interpreted that as false, chrome as true. Now the value is always set to true and will be displayed correctly. But it will not set false (to "hide" the wrapper), which might have possible sideeffacts.

**Comment by ut** [comment]
@Jarami110d I could succesfully open/close the modals ("Popups") in our [preview](https://a-thousand-channels.github.io/a1000c-map-client/) ... can you confirm?

**Comment by Jarami110d** [comment]
Yes!! in the preview is now possible to click on every entry and Pop-up Infos appear. (The only entry with nothing showing is "Queerdance 1996" I assume because it the entry contains no extra information)
Also the -Show details- button is redirecting properly. 
Thanks for the Fix ! 👍 💯

**Comment by ut** [comment]
Thanks for the feedback! I'll take a look on the entry you mentioned (and then take over the fix to our FGTQ clone :)

**Comment by ut** [comment]
FGTQ has the fix also
