### ISSUE TITLE
Error message: Can't fetch map data... :(

### ISSUE THREAD

**Issue by ut** [a-thousand-channels/a1000c-map-client#89]
Only in maps generated via map-to-go

**Comment by ut** [comment]
Thank you!

**Comment by Jarami110d** [comment]
The Map to go I exported last week, running on my localhost, has also the same problem..

**Comment by ut** [comment]
I fixed it ... not really, it's more a hack: I removed the error message. Have to find a better solution, but for the moment it is it

**Comment by Jarami110d** [comment]
ok ! the error message is gone
